import frappe
from email.utils import formataddr

@frappe.whitelist()
def get_engineer_detail(primary_location,secondary_location,service):
	if primary_location and secondary_location and service:
		data = frappe.db.sql("""
			SELECT es_1.user, es_1.full_name, es_1.phone, em.contractor
			FROM `tabEscalation 1` as es_1
			RIGHT JOIN `tabEscalation Matrix` as em ON (es_1.parent = em.name)
			where em.primary_location = '%s' and em.secondary_location = '%s' and em.service = '%s'
			order by es_1.idx
        	limit 1
		""" % (primary_location,secondary_location,service),as_dict=1)

		return data


def issue_validate(self,method):
	escalation_email(self)

def escalation_email(self):
	escalation_1_data = []
	escalation_2_data = []
	escalation_3_data = []

	if frappe.db.exists("Escalation Matrix", {'primary_location':self.primary_location,'secondary_location':self.secondary_location,'service':self.service}):
		escalation_matrix = frappe.get_doc("Escalation Matrix", {'primary_location':self.primary_location,'secondary_location':self.secondary_location,'service':self.service})

		if escalation_matrix:
			for row in escalation_matrix.escalation_1:
				escalation_1_data.append(row.user)
			for row in escalation_matrix.escalation_2:
				escalation_2_data.append(row.user)
			for row in escalation_matrix.escalation_3:
				escalation_3_data.append(row.user)

		#frappe.msgprint(str(escalation_1_data))

		#sender = formataddr(("Collection Department EIEPL", "cd@eieinstruments.com"))

		header_1 = "<p> This email is automatically generated by PID call center to inform you that the task {} has been opened.</p>".format(self.name)
		header_2 = "<p> This email is automatically generated by PID call center to inform you that the task {} has been re-opened as caller informed that issue was not fixed.</p>".format(self.name)
		header_3 = "<p> This email is automatically generated by PID call center to inform you that the task {} has been re-opened as caller informed that issue was not fixed.</p>".format(self.name)

		table_data = """
			<table width="90%" border="1">
				<tbody>
					<tr>
						<td width="40%">
							<p><strong>Task ID #</strong></p>
						</td>
						<td width="60%">
							<p><strong>{0}</strong></p>
						</td>
					</tr>
					<tr>
						<td width="40%">
							<p><strong>Date abd Time</strong></p>
						</td>
						<td width="60%">
							<p><strong>{1}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Contact Type</strong></p>
						</td>
						<td>
							<p><strong>{2}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Task Severity</strong></p>
						</td>
						<td>
							<p><strong>{3}	</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Task Received from </strong></p>
						</td>
						<td>
							<p><strong>{4}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Service Type</strong></p>
						</td>
						<td>
							<p><strong>{5}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Client name</strong></p>
						</td>
						<td>
							<p><strong>{6}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Owner Or Tenant</strong></p>
						</td>
						<td>
							<p><strong>{7}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Mobile Number</strong></p>
						</td>
						<td>
							<p><strong>{8}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Contact Email Address</strong></p>
						</td>
						<td>
							<p><strong>{9}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Primary Location</strong></p>
						</td>
						<td>
							<p><strong>{10}</strong></p>
						</td>
					</tr>
					<tr>
						<td>
							<p><strong>Secondary Location</strong></p>
						</td>
						<td>
							<p><strong>{11}</strong></p>
						</td>
					</tr>	
					<tr>
						<td>
							<p><strong>Issue Description</strong></p>
						</td>
						<td>
							<p><strong>{12}</strong></p>
						</td>
					</tr>
				</tbody>
			</table>
			<br>
			<a href="/desk#Form/Issue/{13}">{14}</a>
			""".format(
				self.name,
				self.opening_date +' ' + self.opening_time,
				self.contact_type or '',
				self.task_severity or '',
				self.task_received_from or '',
				self.service or '',
				self.client_name or '',
				self.owner_or_tenant or '',
				self.contact_mobile or '',
				self.email or '',
				self.primary_location or '',
				self.secondary_location or '',
				self.issue_description or '',
				self.name,
				self.name,
			)
		recipients = []
		if not self.escalation_1_sent:
			recipients = escalation_1_data
			message = header_1 + table_data
			self.db_set('escalation_1_sent',1)
		if self.escalation_counter == 2 and self.contact_type == "Repeated Issue" and not self.escalation_2_sent:
			recipients = escalation_2_data
			message = header_2 + table_data
			self.db_set('escalation_2_sent',1)
		if self.escalation_counter == 3 and self.contact_type == "Repeated Issue" and not self.escalation_3_sent:
			recipients = escalation_3_data
			message = header_3 + table_data
			self.db_set('escalation_3_sent',1)

		recipients = set(recipients)

		#frappe.msgprint(str(recipients))
		if recipients:
			frappe.sendmail(
				recipients=recipients,
				cc = '',
				subject =  "SLA Escalation. Case Number : " + self.name,
				#sender = sender,
				message = message
			)
			
